# Generated by Django 5.0.4 on 2024-04-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_review_rating_review_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='review',
        ),
    ]
