# Generated by Django 5.0.4 on 2024-05-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(blank=True, choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City'), ('historical', 'Historical'), ('food', 'Food'), ('drink', 'Drink')], max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='cons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='pros',
            field=models.TextField(blank=True),
        ),
    ]
